package POJOs;
// Generated 16-ene-2025 19:34:12 by Hibernate Tools 4.3.1



/**
 * Disponible generated by hbm2java
 */
public class Disponible  implements java.io.Serializable {


     private Integer id;
     private Pases pases;
     private Peliculas peliculas;
     private Salas salas;
     private int fila;
     private String letra;
     private String butacas;
     private int estado;
     private int pos;

    public Disponible() {
    }

    public Disponible(Pases pases, Peliculas peliculas, Salas salas, int fila, String letra, String butacas, int estado, int pos) {
       this.pases = pases;
       this.peliculas = peliculas;
       this.salas = salas;
       this.fila = fila;
       this.letra = letra;
       this.butacas = butacas;
       this.estado = estado;
       this.pos = pos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pases getPases() {
        return this.pases;
    }
    
    public void setPases(Pases pases) {
        this.pases = pases;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public int getFila() {
        return this.fila;
    }
    
    public void setFila(int fila) {
        this.fila = fila;
    }
    public String getLetra() {
        return this.letra;
    }
    
    public void setLetra(String letra) {
        this.letra = letra;
    }
    public String getButacas() {
        return this.butacas;
    }
    
    public void setButacas(String butacas) {
        this.butacas = butacas;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public int getPos() {
        return this.pos;
    }
    
    public void setPos(int pos) {
        this.pos = pos;
    }




}


