package POJOs;
// Generated 16-ene-2025 19:34:12 by Hibernate Tools 4.3.1



/**
 * Infogeneral generated by hbm2java
 */
public class Infogeneral  implements java.io.Serializable {


     private String email;
     private String telContacto;
     private String telTaquilla;
     private String parking1;
     private String parking2;
     private String direccion1;
     private String direccion2;
     private String direccion3;
     private String direccion4;
     private String accesoMinusvalido;
     private String sonido;

    public Infogeneral() {
    }

    public Infogeneral(String email, String telContacto, String telTaquilla, String parking1, String parking2, String direccion1, String direccion2, String direccion3, String direccion4, String accesoMinusvalido, String sonido) {
       this.email = email;
       this.telContacto = telContacto;
       this.telTaquilla = telTaquilla;
       this.parking1 = parking1;
       this.parking2 = parking2;
       this.direccion1 = direccion1;
       this.direccion2 = direccion2;
       this.direccion3 = direccion3;
       this.direccion4 = direccion4;
       this.accesoMinusvalido = accesoMinusvalido;
       this.sonido = sonido;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelContacto() {
        return this.telContacto;
    }
    
    public void setTelContacto(String telContacto) {
        this.telContacto = telContacto;
    }
    public String getTelTaquilla() {
        return this.telTaquilla;
    }
    
    public void setTelTaquilla(String telTaquilla) {
        this.telTaquilla = telTaquilla;
    }
    public String getParking1() {
        return this.parking1;
    }
    
    public void setParking1(String parking1) {
        this.parking1 = parking1;
    }
    public String getParking2() {
        return this.parking2;
    }
    
    public void setParking2(String parking2) {
        this.parking2 = parking2;
    }
    public String getDireccion1() {
        return this.direccion1;
    }
    
    public void setDireccion1(String direccion1) {
        this.direccion1 = direccion1;
    }
    public String getDireccion2() {
        return this.direccion2;
    }
    
    public void setDireccion2(String direccion2) {
        this.direccion2 = direccion2;
    }
    public String getDireccion3() {
        return this.direccion3;
    }
    
    public void setDireccion3(String direccion3) {
        this.direccion3 = direccion3;
    }
    public String getDireccion4() {
        return this.direccion4;
    }
    
    public void setDireccion4(String direccion4) {
        this.direccion4 = direccion4;
    }
    public String getAccesoMinusvalido() {
        return this.accesoMinusvalido;
    }
    
    public void setAccesoMinusvalido(String accesoMinusvalido) {
        this.accesoMinusvalido = accesoMinusvalido;
    }
    public String getSonido() {
        return this.sonido;
    }
    
    public void setSonido(String sonido) {
        this.sonido = sonido;
    }




}


